version: '3.8'

services:
  passkey-panel:
    image: webdevops/php-apache:8.2
    ports:
      - "8060:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/panel
    command: bash -c "rm -rf /app/* && git clone https://github.com/tvagenciariver/waha-passkey.git /app && supervisord"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
