version: '3.8'

services:
  passkey-panel:
    image: nginx:alpine
    ports:
      - "8060:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
